"""
Django settings for ssl_manager project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pclylnls(9__8255@gbwm-1%17$^@9_y9+i)&ay#21g50-dqi@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_python3_ldap',
    'certificates',
]

AUTH_USER_MODEL = 'certificates.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'certificates.language_middleware.UserLanguageMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ssl_manager.middleware.PasswordExpirationMiddleware',
    'certificates.middleware.MFAMiddleware',
]

ROOT_URLCONF = 'ssl_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ssl_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('pt', 'Português'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
    ('it', 'Italiano'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Map Django message tags to Bootstrap alert classes
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}


# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'certificates.backends.SourceAwareLDAPBackend',
    'certificates.backends.SourceAwareModelBackend',
]

# LDAP Configuration
# These settings should be customized for your LDAP/AD server
LDAP_AUTH_URL = "ldap://localhost:389"  # Change to your LDAP server URL
LDAP_AUTH_USE_TLS = False  # Set to True for production
LDAP_AUTH_SEARCH_BASE = "ou=users,dc=sslmanager,dc=local"  # Change to your LDAP base DN
LDAP_AUTH_OBJECT_CLASS = "inetOrgPerson"  # Common for OpenLDAP, use "user" for Active Directory
LDAP_AUTH_USER_FIELDS = {
    "username": "uid",  # For Active Directory, use "sAMAccountName"
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)
LDAP_AUTH_CLEAN_USER_DATA = "certificates.ldap_sync.clean_user_data"
LDAP_AUTH_SYNC_USER_RELATIONS = "certificates.ldap_sync.sync_user_relations"
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "certificates.ldap_sync.format_search_filters"
LDAP_AUTH_FORMAT_USERNAME = "certificates.ldap_sync.format_username"

# CRITICAL: Prevent auto-creation of users - users must be pre-registered
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = None  # Set to your AD domain if using AD (e.g., "MYCOMPANY")
LDAP_AUTH_CONNECTION_USERNAME = "cn=admin,dc=sslmanager,dc=local"
LDAP_AUTH_CONNECTION_PASSWORD = "admin123"
