# Generated by Django 5.2.8 on 2025-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='country',
            field=models.CharField(default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='domain',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='domain',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domain',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domain',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domain',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
