# Generated by Django 5.2.8 on 2025-11-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_domain_country_domain_email_address_domain_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateentry',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateentry',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
