# Generated by Django 5.2.8 on 2025-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificateentry_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ISSUED', 'Issued'), ('SIGNED', 'Signed'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20),
        ),
    ]
