# Generated by Django 5.2.8 on 2025-11-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_cookieconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('pt', 'Português'), ('fr', 'Français'), ('de', 'Deutsch'), ('it', 'Italiano')], default='en', max_length=10),
        ),
    ]
