# Generated by Django 5.2.8 on 2025-12-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_user_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SSL Manager Internal CA', max_length=255)),
                ('root_ca_cert', models.TextField(help_text='Root CA certificate (PEM format)')),
                ('root_ca_key', models.TextField(help_text='Root CA private key (PEM format)')),
                ('intermediate_ca_cert', models.TextField(help_text='Intermediate CA certificate (PEM format)')),
                ('intermediate_ca_key', models.TextField(help_text='Intermediate CA private key (PEM format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one CA should be active')),
            ],
            options={
                'verbose_name': 'Internal CA',
                'verbose_name_plural': 'Internal CAs',
            },
        ),
        migrations.AddField(
            model_name='certificateentry',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Certificate generated by internal CA'),
        ),
    ]
